<a href="https://colab.research.google.com/github/AttiBae/BasicML/blob/main/Chapter_1_Make_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
!pip install torchvision

In [ ]:
import torch

In [ ]:
x = torch.rand(10)

In [ ]:
x_tensor = torch.tensor(10)

In [ ]:
print(x)
print(x_tensor)
x.size()
print(x_tensor.dim())

tensor([0.9473, 0.4276, 0.6994, 0.6864, 0.0055, 0.2596, 0.5360, 0.4761, 0.1719,
        0.9682])
tensor(10)
0


In [ ]:
x = torch.autograd.Variable(torch.ones(2,2), requires_grad = True)
y = x.mean()

y.backward()

print('Gradient of x : \n{}\n'.format(x.grad))
print('Gradient function of x : {}\n'.format(x.grad_fn))
print('Gradient function of y : {}\n'.format(y.grad_fn))
print('Data of x : \n{}'.format(x.data))

Gradient of x : 
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

Gradient function of x : None

Gradient function of y : <MeanBackward0 object at 0x7f58f671a290>

Data of x : 
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
import numpy as np
from torch.autograd import Variable as Variable

train_x = np.asarray([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9])
train_y = np.asarray([9.1,8.2,7.3,6.5,5.6,4.7,3.8,2.9,1.0])

X = Variable(torch.from_numpy(train_x).type(torch.FloatTensor), requires_grad = False)
Y = Variable(torch.from_numpy(train_y).type(torch.FloatTensor), requires_grad = False)

In [ ]:
import numpy as np
from torch.autograd import Variable as Variable
dtype = torch.FloatTensor

train_x = np.asarray([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9])
train_y = np.asarray([9.1,8.2,7.3,6.5,5.6,4.7,3.8,2.9,1.0])

X = Variable(torch.from_numpy(train_x).type(dtype), requires_grad = False)
Y = Variable(torch.from_numpy(train_y).type(dtype), requires_grad = False)

In [ ]:
torch.cuda.is_available()

True

In [ ]:
import time

a = torch.rand(4716, 4716)
b = torch.rand(4716, 4716)

start = time.time()
a. matmul(b)
time_taken = time.time() - start

print('Time taken with CPU : {:0.4}s '.format(time_taken))

a = a.cuda()
b = b.cuda()

start = time.time()
a. matmul(b)
time_taken = time.time() - start
print('Time taken with CUDA : {:0.4}ms'.format(time_taken * 1e3))

Time taken with CPU : 2.48s 
Time taken with CUDA : 10.06ms
